export const products = [
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e898",
        "name": "UltraView Pro X3",
        "brand": "Gigabyte",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X3. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDb.",
        "category": "Monitores",
        "img": "https://i.imgur.com/nKeotAS.png",
        "price": 39.99,
        "quantity": 15,
        "sales": 10,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e899",
        "name": "UltraView Pro X4",
        "brand": "LG",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X4. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDc.",
        "category": "Monitores",
        "img": "https://i.imgur.com/bNa8HuU.png",
        "price": 45.99,
        "quantity": 20,
        "sales": 5,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89a",
        "name": "UltraView Pro X5",
        "brand": "LG",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X5. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDd.",
        "category": "Monitores",
        "img": "https://i.imgur.com/moZHQc9.png",
        "price": 42.99,
        "quantity": 18,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89b",
        "name": "UltraView Pro X6",
        "brand": "Philips",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X6. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDe.",
        "category": "Monitores",
        "img": "https://i.imgur.com/Z6EUOdX.png",
        "price": 37.99,
        "quantity": 25,
        "sales": 8,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89c",
        "name": "UltraView Pro X7",
        "brand": "MSI",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X7. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDf.",
        "category": "Monitores",
        "img": "https://i.imgur.com/NjTZ0Yq.png",
        "price": 40.99,
        "quantity": 22,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89d",
        "name": "UltraView Pro X8",
        "brand": "ViewSonic",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X8. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDg.",
        "category": "Monitores",
        "img": "https://i.imgur.com/QgwlLA9.png",
        "price": 38.99,
        "quantity": 17,
        "sales": 12,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89e",
        "name": "UltraView Pro X9",
        "brand": "Gigabyte",
        "description": "Experimenta la última innovación en visualización con el monitor UltraView Pro X9. Este monitor de vanguardia presenta una pantalla curva de 32 pulgadas con una resolución 4K UHDh.",
        "category": "Monitores",
        "img": "https://i.imgur.com/nh6Bshc.png",
        "price": 36.99,
        "quantity": 30,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e89f",
        "name": "SonicWave Pro",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/arEIFVa.png",
        "price": 49.99,
        "quantity": 10,
        "sales": 5,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a0",
        "name": "SonicWave Pro a",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro a. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/fyhDHmT.png",
        "price": 53.99,
        "quantity": 15,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a1",
        "name": "SonicWave Pro b",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro b. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/7VmJ1yi.png",
        "price": 48.99,
        "quantity": 20,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a2",
        "name": "SonicWave Pro d",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro d. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/lQg0zDM.png",
        "price": 51.99,
        "quantity": 18,
        "sales": 8,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a3",
        "name": "SonicWave Pro e",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro e. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/9i8hf34.png",
        "price": 46.99,
        "quantity": 25,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a4",
        "name": "SonicWave Pro f",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro f. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/8TzpoMg.png",
        "price": 50.99,
        "quantity": 22,
        "sales": 0,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a5",
        "name": "SonicWave Pro g",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro g. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/ScSmkG6.png",
        "price": 52.99,
        "quantity": 17,
        "sales": 12,
        "deleted": false
    },
    {
        "sale": 0,
        "_id": "656ece33cb93524e81b8e8a6",
        "name": "SonicWave Pro h",
        "brand": "Sony",
        "description": "Sumérgete en el mundo de la música, los juegos y las llamadas con los Auriculares SonicWave Pro h. Estos auriculares inalámbricos de última generación ofrecen una calidad de sonido excepcional y una comodidad incomparable.",
        "category": "Auriculares",
        "img": "https://i.imgur.com/EIbdBKz.png",
        "price": 47.99,
        "quantity": 30,
        "sales": 0,
        "deleted": false
    }
]